# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f909b4f739c0605d7f63166950137e873a957e67ef69b9df5167496bb1f28d24c5a5665bdffccf3c87383d9cc554b6050a22568adbf00527d86ee02ba0b02f

test:
  secret_key_base: a9ff04c6455b2f5434cd7baad1305049c45b58903b8b9d90e982a6486e0671b120f45f763c67adf5e7fd36c7b639e323cbf66aabab8fce4ea3b937ff3041ae61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
